import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import type { GetServerSideProps, NextPage } from "next";
import { urqlClient } from "../libs/gql-requests";
import gql from "graphql-tag";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  posts: {
    id: string;
    title: string;
  }[];
};

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  try {
    const client = await urqlClient();

    // 変数なしでGraphQL呼び出し
    const postsQuery = gql`
      query {
        posts {
          id
          title
        }
      }
    `;
    const result = await client.query(postsQuery, {}).toPromise();
    console.log(result.data);

    return {
      props: {
        posts: result.data.posts,
      },
    };
  } catch (e) {
    console.error(e);
    return {
      notFound: true,
    };
  }
};

const Home: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Hello, GraphQL</h1>
        <ul className={styles.grid}>
          {props.posts.map((post) => (
            <li className={styles.title} key={post.id}>
              id: {post.id} title: {post.title}
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}

export default Home;
